### ISSUE TITLE
Blur in Plasma

### ISSUE THREAD

**Issue by archisman-panigrahi** [manilarome/rofi-spotlight#12]
Is it possible to use blur in `rofi-spotlight` in KDE Plasma? In Plasma, the background of Rofi is transparent, but there is no blur.

I have already enabled blur in Desktop effects. I also tried to use the Force Blur script on `rofi`, but it did not work (However, the force blur script works in Firefox with `blurredfox`).

**Comment by eromatiya** [comment]
I saw someone posted on r/unixporn that has his rofi with blur. Although I'm not sure myself on how to achieve it (I don't have Plasma installed so can't test it), sorry. So yeah, closing this now.
