### ISSUE TITLE
Broken results while navigating under FD

### ISSUE THREAD

**Issue by eromatiya** [manilarome/rofi-spotlight#14]
Can be reproduced if `fd` is installed. `for i in *` works well.

![fishblock](https://user-images.githubusercontent.com/40349590/93568332-92cb7380-f9c2-11ea-8f1b-231333b573bf.png)

**Comment by eromatiya** [comment]
@AethanFoot could you please help me with this? [These lines](https://github.com/manilarome/rofi-spotlight/blob/a36ec45c9b15fdb8eb0a123774458a4e9268b530/rofi-spotlight.sh#L462-L470) are probably the issue. Thanks!

**Comment by AethanFoot** [comment]
Can you run the fd -H -d 1 in the folder and an ls to compare the output

**Comment by eromatiya** [comment]
The outputs are the same:

![image](https://user-images.githubusercontent.com/40349590/93572742-d9bc6780-f9c8-11ea-8334-317fca754c9c.png)

Note that I can also reproduced this problem on all directories with files. And the thumbnails generated from image files are not showing/missing, while the icons from icon pack (tela/papirus/etc.) are showing properly. There's also problem with *first* whitespace again. I tried fixing it but I'm really at my wits end haha.
