### ISSUE TITLE
Edit and open in terminal not working

### ISSUE THREAD

**Issue by AethanFoot** [manilarome/rofi-spotlight#3]
Everything but opening a file to edit it and opening the file in terminal doesn't work, I've set the editor to nvim and term to alacritty.

**Comment by AethanFoot** [comment]
I've fixed opening a file to edit it by putting -e after the term in the context menu, but haven't had any luck with what ive tried with opening the location in term

**Comment by eromatiya** [comment]
>Everything but opening a file to edit it and opening the file in terminal doesn't work, I've set the editor to nvim and term to alacritty.

Does it work if you're using kitty? There must be a difference of command parameters or something. 


Please try to run this on your terminal. This is the command to open the file path in terminal. Just set the `file_path` variable and change the kitty with your terminal emulator.

```bash
$ file_path=/PATH/TO/SOMETHING.JPG
$ coproc ( kitty bash -c "cd '${file_path%/*}' ; ${SHELL}" &> /dev/null 2>&1 )
```

Anyway, what's your shell? I have a suspicion that ${SHELL} is the cause of the problem. I'm using ZSH.

**Comment by AethanFoot** [comment]
Hi thanks for the reply I've managed to get it working

**Comment by eromatiya** [comment]
Can I ask you how? In case someone encounter the same problem in the future.

**Comment by AethanFoot** [comment]
Ah yes, it was just a -e after the term again, some how messed that up while tired in my first testing

**Comment by eromatiya** [comment]
Thanks!
